追加：料理入力フォーム（登録・編集用）のフロントバリデーション機能の実装
hiroto0423/meal-team-Development pull request #10
Opened 2022-08-29 07:01 UTC by Garbage-soft

料理登録フォーム、編集フォーム用のフロントエンド側のバリデーション機能を作成しました。

2022-08-29 07:09 UTC, Garbage-soft commented on src/public/js/front_form_validation.js
> +  const inputCost        = document.getElementById('inputCost');
画面オブジェクトをidで取得し、変数に格納しています。

2022-08-29 07:09 UTC, Garbage-soft commented on src/public/js/front_form_validation.js
> +    }
取得した画面オブジェクトのvalueを検証し、配列message　にエラーメッセージを格納しています。

2022-08-29 07:09 UTC, Garbage-soft commented on src/resources/views/meals/create.blade.php
> -                </div>
フォームの中に写真を投稿するフォームがあったので暫定的な修正をしました。
送信ボタンを削除しました。

また別途、画像投稿に関する修正を行います。

2022-08-29 07:09 UTC, Garbage-soft commented on src/resources/views/meals/create.blade.php
> +              <input type="text" placeholder="オムライス" name="名前" id="inputMealName">
バリデーションが必要な　inputタグ群　に id を定義しました。

2022-08-29 07:48 UTC, Garbage-soft commented on src/resources/views/meals/create.blade.php
> +      <script src="js/front_form_validation.js"></script>
今回作成したJSファイルを読み込んでいます。

2022-08-29 09:56 UTC, hiroto0423 commented on src/public/js/front_form_validation.js
> +    }
配列にメッセージを追加していくんですね　勉強になります
バリューは空白以外に文字数の制限のバリデーションが必要だと感じました

2022-08-29 11:08 UTC, Garbage-soft commented on src/public/js/front_form_validation.js
> +    }
了解しました。　文字数制限のバリデーションを追加します

2022-08-29 11:21 UTC, Garbage-soft commented on src/public/js/front_form_validation.js
> +    }
料理名の文字数制限 50文字 
今回追加した各バリデーションにはエラー文と現在の文字数を確認できるようにしています

2022-08-29 11:21 UTC, Garbage-soft commented on src/public/js/front_form_validation.js
> +    }
材料メモの文字数制限　200文字
メッセージにはエラー文と現在の文字数を確認できるようにしています

2022-08-29 11:21 UTC, Garbage-soft commented on src/public/js/front_form_validation.js
> +    }
作り方の文字数制限　500文字
メッセージにはエラー文と現在の文字数を確認できるようにしています

2022-08-29 11:21 UTC, Garbage-soft commented on src/public/js/front_form_validation.js
> +    }
材料メモの文字数制限 200文字のバリデーション

2022-08-29 11:21 UTC, Garbage-soft commented on src/public/js/front_form_validation.js
> +    }
作り方の文字数制限 500文字のバリデーション

2022-08-30 05:52 UTC, YuukiTakao requested changes
@Garbage-soft @hiroto0423 
バリデーションが動いてました！
１点出てない要素があったのでそこだけ修正お願いします！
あとは、余力があればIMOでコメントしました〜

2022-08-30 05:52 UTC, YuukiTakao commented on src/public/js/front_form_validation.js
> +      message.push("コストには数値を入力してください。")
<img width="279" alt="スクリーンショット 2022-08-30 14 39 10" src="https://user-images.githubusercontent.com/34182949/187358165-aa11af8b-fb0a-4609-abbd-ae27a7c12bd5.png">
[IMO]
プレースホルダーには文字列が入ってますが、︎数値を強制させてるので統一したい気持ち

2022-08-30 05:52 UTC, YuukiTakao commented on src/public/js/front_form_validation.js
> +  const inputCost        = document.getElementById('inputCost');
[IMO]
formオブジェクトから取得した方がわかりやすいですね！

参考
https://atmarkit.itmedia.co.jp/ait/articles/1609/01/news072.html

2022-08-30 05:52 UTC, YuukiTakao commented on src/public/js/front_form_validation.js
> +    const REGEX = /[0-9]/
[IMO]
定数名が少し分かりにくいかも。
何に使う定数名かわかった方が良さそうですね

`COST_REGEX`とか

さらにいうと今回の場合は、一箇所でしか使われてないのでコストのif文に直接書いてあった方がわかりやすいかもしれないですね。

2022-08-30 05:52 UTC, YuukiTakao commented on src/public/js/front_form_validation.js
> +    //　エラーメッセージを格納する配列を定義
変数名を `errorMessages`とかにしたらコメントを消せる気がしますがいかがでしょう？

2022-08-30 05:52 UTC, YuukiTakao commented on src/resources/views/meals/create.blade.php
>              <h1>料理登録</h1>
<img width="1026" alt="スクリーンショット 2022-08-30 14 49 30" src="https://user-images.githubusercontent.com/34182949/187359490-1c43a48b-7170-49ab-866a-9fcdb9f110b8.png">
`<h1>料理登録</h1>`が画面に出てないので直したいですね

2022-08-30 07:09 UTC, Garbage-soft commented on src/public/css/style.css
>  .random-button button {
ヘッダーに見出しが埋もれていたのでCSSを修正しました。

2022-08-30 07:09 UTC, Garbage-soft commented on src/public/css/style.css
> +    /* background-color:; */
不明な記述をコメント化しました

2022-08-30 07:09 UTC, Garbage-soft commented on src/public/js/front_form_validation.js
> +  const inputCost        = document.meal_form.meal_cost
フォームオブジェクトを取得しています

2022-08-30 07:09 UTC, Garbage-soft commented on src/public/js/front_form_validation.js
> +
コメントを削除し、配列名を分かるように変更しました。

2022-08-30 07:09 UTC, Garbage-soft commented on src/public/js/front_form_validation.js
>    })
バリデーション処理に必要な箇所を書き換えています。

2022-08-30 07:09 UTC, Garbage-soft commented on src/resources/views/meals/create.blade.php
>              <h1>料理登録</h1>
CSSを修正して表示させました。

2022-08-30 08:00 UTC, YuukiTakao approved these changes
@Garbage-soft 
LGTM!
ただ、コメント追加してるのでご確認お願いシャス！
![ミサワ](https://livedoor.blogimg.jp/jigokuno_misawa/imgs/0/3/038fd4dc.gif)

2022-08-30 08:00 UTC, YuukiTakao commented on src/public/css/style.css
> +    /* background-color:; */
不要であれば削除した方がいいと思いました！

2022-08-30 08:00 UTC, YuukiTakao commented on src/public/js/front_form_validation.js
> +    if(!/[0-9]/.test(inputCost.value)) {
:+1:

2022-08-30 08:00 UTC, YuukiTakao commented on src/resources/views/meals/create.blade.php
>                <h2>料理名</h2>
[IMO]
今気づいたんですが、フォームのラベルが見出しであるh2タグ使ってるのは違和感ありますね。。
シンプルlabelタグで良い気がします

2022-08-30 08:55 UTC, Garbage-soft commented on src/resources/views/meals/create.blade.php
> +              <label>満腹度</label>
h2タグからlabelタグに変更しました

2022-08-30 08:57 UTC, merged