料理詳細APIの作成
hiroto0423/meal-team-Development pull request #11
Opened 2022-08-29 09:02 UTC by hiroto0423

料理詳細のAPIを作成しました

2022-08-29 09:18 UTC, hiroto0423 commented on src/app/Http/Controllers/MealController.php
> +        $item = \App\Meal::find($request[0]);
repuestで送ったmealテーブルのidに関するデータベースのレコードを取得

2022-08-29 09:18 UTC, hiroto0423 commented on src/public/js/meal_read.js
> +    var id = result[result.length - 1];
現在アクセスしているURLの階層を取得し、配列の一番後ろにあるidの値を変数として取得

2022-08-29 09:18 UTC, hiroto0423 commented on src/public/js/meal_read.js
> +            body: JSON.stringify(id)
http://localhost:9000/api/mealread　に対して、取得したidをjson形式でpostする

2022-08-29 09:18 UTC, hiroto0423 commented on src/public/js/meal_read.js
> +            var meal_difficulty = response['difficulty']
responseで返ってきたDBのレコードデータを変数として取得

2022-08-29 09:18 UTC, hiroto0423 commented on src/public/js/meal_read.js
> +            var meal_read_difficulty = document.getElementById('meal_difficulty');
HTMLファイルのIDを変数として取得

2022-08-29 09:18 UTC, hiroto0423 commented on src/public/js/meal_read.js
> +            meal_read_difficulty.innerHTML = meal_difficulty;
HTMLの要素の中身を変更

2022-08-29 09:18 UTC, hiroto0423 commented on src/routes/api.php
> +Route::post('mealread','MealController@mealread');
料理詳細APIに対するルーティングの作成

2022-08-30 03:47 UTC, Garbage-soft commented on src/app/Http/Controllers/MealController.php
> +        $item = \App\Meal::find($request[0]);
確認しました

2022-08-30 03:47 UTC, Garbage-soft commented on src/public/js/meal_read.js
> +    var id = result[result.length - 1];
6,7行目の id取得の記述が分かりにくいので（特に７行目）

6行目
const params = url.serchParams;

7行目
const meal_id = params.get('id');


としてください。
変数id として定義していたところは全て　meal_id に置換をお願いします。

(単純に　id　として定義しても良いのですが、何を指しているのか分かりずらいので、取り扱っているDBに関するid として　meal_id　としました)

参考:
http://var.blog.jp/archives/72768336.html

2022-08-30 03:47 UTC, Garbage-soft commented on src/public/js/meal_read.js
> +            body: JSON.stringify(id)
確認しました

2022-08-30 03:47 UTC, Garbage-soft commented on src/public/js/meal_read.js
> +            var meal_difficulty = response['difficulty']
確認しました。

2022-08-30 03:47 UTC, Garbage-soft commented on src/public/js/meal_read.js
> +            var meal_read_difficulty = document.getElementById('meal_difficulty');
確認しました

2022-08-30 03:47 UTC, Garbage-soft commented on src/public/js/meal_read.js
> +            meal_read_difficulty.innerHTML = meal_difficulty;
確認しました

2022-08-30 03:47 UTC, Garbage-soft commented on src/routes/api.php
> +Route::post('mealread','MealController@mealread');
確認しました

2022-08-30 05:12 UTC, Garbage-soft commented on src/public/js/meal_read.js
> +    var id = result[result.length - 1];
↑に関してはリファクタリングするフェーズ（リリース後）に行いたいと思います

2022-08-30 08:33 UTC, YuukiTakao requested changes
@hiroto0423 修正と確認お願いします！

2022-08-30 08:33 UTC, YuukiTakao commented on src/public/js/meal_read.js
> +    var id = result[result.length - 1];
@Garbage-soft @hiroto0423 
僕の経験にはなりますが、リリース後にそのコードを触るのはいつになるか分からないので、リファクタリングはリリースする前にやることが多いです〜

2022-08-30 08:33 UTC, YuukiTakao commented on src/public/js/meal_read.js
> +            body: JSON.stringify(id)
@hiroto0423 
restの考え方で、uriで指定するのはリソース（名詞系が基本。ただしsearchなど例外も普通にある）になり、httpのメソッドでそのリソースを操作できるようなインターフェースで設計するのが基本とされています。

なので、bodyでidを受け渡すより、URLのパスに含む方がrestの流儀なのでここは直し方がいいと感じてますがどうでしょう？

参考：https://meetup-jp.toast.com/931#4-1_REST_API

2022-08-30 08:33 UTC, YuukiTakao commented on src/public/js/meal_read.js
> +    console.log( 'Hello World' );
デバッグログはリリース前には綺麗にしたいですね！

2022-08-30 08:33 UTC, YuukiTakao commented on src/public/js/meal_read.js
> +            //HTMLファイルのIDを変数として取得
[FYI]
`idを変数として`
という記載に少し不安を覚えました！
id属性を元にHTMLElementオブジェクトを取得してという処理だと思うので、jsからHTMLを扱うときにjsのオブジェクトとして処理しているということは理解できてるか確認してみてください。:+1:

参考https://developer.mozilla.org/ja/docs/Web/API/HTMLElement

2022-08-30 08:33 UTC, YuukiTakao commented on src/public/js/meal_read.js
> +            console.log(error);
[IMO]
これだとエラー発生時にユーザーは画面上で何も起きなくて、迷子になってしまう気がしましたがいかがでしょうか？

2022-08-30 08:33 UTC, YuukiTakao commented on src/routes/api.php
> +Route::post('mealread','MealController@mealread');
restっぽくない（動詞系）エンドポイントは直したいですね！

2022-08-31 09:54 UTC, hirototakano commented on src/public/js/meal_read.js
> +            //HTMLファイルのIDを変数として取得
指摘ありがとうございます。確認します！

2022-08-31 09:54 UTC, hirototakano commented on src/public/js/meal_read.js
> +            console.log(error);
その通りですね、料理登録画面にリダイレクトするように変更します

2022-08-31 09:54 UTC, hirototakano commented on src/public/js/meal_read.js
> +    console.log( 'Hello World' );
承知しました！

2022-08-31 09:54 UTC, hirototakano commented on src/public/js/meal_read.js
> +            body: JSON.stringify(id)
直します！

2022-08-31 09:54 UTC, hiroto0423 commented on src/public/js/meal_read.js
> +        fetch(url+endpoint_mealread + id, {
bodyでidを受け渡すより、URLのパスに含む方法に変更しました

2022-08-31 09:54 UTC, hiroto0423 commented on src/routes/api.php
> +Route::get('meal/{meal}','MealController@mealread');
restにのっとって動詞形のエンドポイントを変更しました

2022-08-31 17:17 UTC, YuukiTakao requested changes
@hiroto0423 
もうちょいですね！いい感じですよー！

2022-08-31 17:17 UTC, YuukiTakao commented on src/public/js/meal_read.js
> +            // body: JSON.stringify(id)
コメントアウトしてる部分は消して綺麗にしちゃいましょう:+1:

2022-08-31 23:30 UTC, Garbage-soft commented on src/public/js/meal_read.js
> +    var id = result[result.length - 1];
@hiroto0423 

これで１行でURLに含まれる id が取得できますね

// http:// ~ /meals/xx xxの部分の取得
param_id = location.pathname.split('/').pop();

2022-09-20 10:20 UTC, merged